---
- name: include debian distro variables
  include_vars: "debian.yml"

- name: Install JAVA 8. #recommended
  yum:
    name: "{{java.VERSION}}" #easy to initialize like this else name directory
    state: present
  become: true

- name: Correct alternative java installations.
  alternatives:
    name: java
    link: /bin/java
    path: "{{java.ALTERNATIVES}}"

- name: add jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: add jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true
  when: jenkins_repo_url != ""

- name: download latest jenkins -ver from store.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_2.156_all.deb"
    dest: "/tmp/jenkins_2.156_all.deb"
  when: latest jenkins version to install

- name: install_Jenkins.
  apt:
    deb: "/tmp/jenkins_2.156_all.deb"   #latest in store
    state: present
  when: jenkins_version is not defined
  notify: configure default users

- name: set jenkins JAVA options
  lineinfile:
    dest=/etc/sysconfig/jenkins
    regexp=^JENKINS_JAVA_OPTIONS=
    line=JENKINS_JAVA_OPTIONS="{{jenkins.JAVA_OPTIONS}}"
  become: true

- name: start jenkins service @ start.
  service:
    name: jenkins
    state: started
    enabled: yes
